### PR TITLE
Added a new CLI subcommand `pipe`

### PR DESCRIPTION
**Pull request by sokorototo**
Added a new `pipe` subcommand, that allows you to read only a specific resource from an Archive into stdout. You can then pipe the stream wherever you deem necessary: `jq`, into a file or dumped into your terminal.

Sample Usage:

```sh
# Here -r stands for Resource
vach pipe -i documents.vach -r malbolgea.json

{
  "name": "Malbolgea",
  "type": "Fantasy World",
  "description": "Malbolgea is a fantastical realm filled with magic, mythical creatures, and ancient civilizations. It is a world of adventure and danger, where heroes rise to challenge dark forces and explore forgotten ruins.",
  "regions": [
    {
      "name": "The Verdant Forest",
      "description": "A lush and vibrant forest teeming with life. Ancient trees reach for the sky, and sunlight filters through the dense canopy, casting dappled shadows on the forest floor. But beware, for within the depths of the forest, strange and magical creatures lurk."
    },
    {
      "name": "The Crimson Mountains",
      "description": "Towerous peaks shrouded in mist and mystery. The Crimson Mountains are home to ancient dwarven strongholds, hidden valleys, and treacherous passes. Adventurers brave enough to explore these rugged lands may uncover forgotten treasures or awaken ancient evils."
    },
    {
      "name": "The Shifting Sands",
      "description": "Endless dunes stretch as far as the eye can see, shifting and changing with the wind. Beneath the scorching sun, ruins of lost civilizations lie buried, waiting to be discovered by intrepid explorers. But the sands hold more than secrets—they hold danger and deception."
    }
  ],
  "characters": [
    {
      "name": "Aria Moonshadow",
      "race": "Elf",
      "class": "Ranger",
      "description": "A skilled archer and tracker, Aria roams the forests of Malbolgea, protecting its creatures and preserving its natural beauty. With her keen senses and elven grace, she is a formidable ally and a fierce opponent to those who threaten the balance of nature."
    },
    {
      "name": "Dorn Stonehammer",
      "race": "Dwarf",
      "class": "Warrior",
      "description": "A veteran of many battles, Dorn is a stalwart defender of his people and their mountain strongholds. With his mighty axe and indomitable spirit, he faces danger head-on, whether battling orcs in the depths of the mountains or exploring ancient ruins in search of lost treasures."
    },
    {
      "name": "Zephyr Sandwalker",
      "race": "Human",
      "class": "Sorcerer",
      "description": "A master of arcane magic, Zephyr wields power beyond mortal comprehension. With a flick of his wrist, he can summon storms, control the elements, or unleash devastating spells upon his enemies. But his powers come with a price, and he must constantly guard against the lure of dark magic."
    }
  ]
}

```

### CODE REVIEW

**Comment by zeskeertwee** [comment]
Looks good, but why remove log?

**Comment by sokorototo** [comment]
I removed `log` since mostly errors or success messages are logged. I just log errors with `eprintln` since it prints out to stderr anyways, other messages are logged via the progress bar

**Comment by zeskeertwee** [comment]
Log also allows underlying dependencies to log things though, and it's a very small dependency anyway.

**Comment by sokorototo** [comment]
> Log also allows underlying dependencies to log things though, and it's a very small dependency anyway.

Running `cargo tree` in the root of the `vach-cli` crate, I can't see any crates using the `log` crate. So I just decided to not use it, rather than use it and add a few colours on exactly one error message. The log crate is generally useful for server applications and other long lived high availability applications. I think `println` and `eprintln` are enough for us.

**Review by zeskeertwee — APPROVED** [review]

**Pull request merged**
