### PR TITLE
This PR comes with it the new `Archive::fetch_batch(---)` function and changes to some dependencies

### PR DESCRIPTION
**Pull request by sokorototo**
- Well first my repo is bugged out (again) so you will see more commits than there actually are. They are only about 14.
 - I have added the new `Archive::fetch_batch(---)` function for loading multiple assets in parallel
 - Changed from `aes_gcm_siv` to `aes_gcm` for more performance in encryption
 - I also changed the `max_width` key in `rustfmt.toml` since a width of 100 kept making the code wrap
 - I changed the `Builder::dump(---)` fn to use `AtomicUsize` instead of `Arc<Mutex<usize>>`
 - I changed the `API` for the compressor struct to be more flexible and memory intensive
 - I improved the `vach-pack` CLI subcommand to use a multithreaded builder and to update the progress bar more accurately
 - amogus

### CODE REVIEW

**Comment by sokorototo** [comment]
Yeah also review the merge conflicts

**Review by zeskeertwee — APPROVED** [review]
Looks awesome!

**Comment by sokorototo** [comment]
You need to resolve the merge conflicts, it's quite easy with vscode

**Comment by sokorototo** [comment]
Yeah I "resolved" the merge conflicts

**Pull request merged**
